name: Build wheels

on:
  push:
    branches:
     - 'main'
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]
        python-version: [cp38, cp39, cp310, cp311]
        arch: [arm64]

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install cibuildwheel
      run: python3 -m pip install cibuildwheel==2.11.2

    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3

    - name: Build wheels
      run: python3 -m cibuildwheel --output-dir wheelhouse
      env:
        CIBW_BUILD: ${{ matrix.python-version }}-*
        CIBW_ARCHS_MACOS: ${{ matrix.arch }}
        CIBW_BUILD_FRONTEND: build
        GMP_ROOT: /Users/runner/work/${{ github.event.repository.name }}/${{ github.event.repository.name }}/arm-homebrew/opt/gmp
        CIBW_BEFORE_BUILD: ./.github/scripts/mac_install_gmp.sh
        CIBW_ENVIRONMENT: SYMFORCE_REWRITE_LOCAL_DEPENDENCIES=True

    - name: Upload wheels
      uses: actions/upload-artifact@v3
      with:
        name: symforce-wheels
        path: wheelhouse/*.whl
